### ISSUE TITLE
建议 kissy-gallery / gallery / huabao 支持无数据源配置

### ISSUE THREAD

**Issue by huanglong-zz** [kissygalleryteam/kissy-gallery#101]
## huabao 组件现在支持两种数据源方式：
1. 页面中的 json；
2. 通过 ajax 返回的远程数据。

单独再提供一个异步接口来返回这种数据格式的开发成本还是有的，建议是加上支持无数据源的配置项，即数据是一开始就通过后台输出到页面上的，画报组件初始化之即可。

**Comment by pushiming** [comment]
> 数据是一开始就通过后台输出到页面上

就是这里说的“页面中的 json”

**Comment by huanglong-zz** [comment]
哦，是我没描述准确。
是一开始就将缩略图，大图，描述这些数据输出到页面对应的dom节点中，不用json的方式，也不需要用到templet。这种对于开发者，尤其是后台开发工程师比较友好。他不需要 care json格式，json接口，直接就能从展现上输出信息。画报组件增加这个对 huabao 节点初始化的工作，支持里面的切换就可以了。

**Comment by pushiming** [comment]
按照你的需求，貌似直接用一个 switchable 装饰上去应该就可以了吧？画报这个主要是业务 model 这一块比较特殊

**Comment by huanglong-zz** [comment]
对，我后来就是把画报里切换这一块儿的逻辑剥离出来单独使用了，这样静态数据也利于seo。不过 model 层还是会用到的，翻页后的异步数据处理，包括缩略图的移动逻辑还是蛮精致的，就不想再去用switchable改造了。我想，画报增加一个配置功能应该更利于推广和使用，也不会额外增加多少复杂度。

**Comment by pushiming** [comment]
亲，非常感谢……不过现在画报已经基本下线了，全线迁移到了 [顽兔](http://wantu.taobao.com/)
