### ISSUE TITLE
【KF/Uploader】多图上传图片数目限制问题

### ISSUE THREAD

**Issue by shepherdwind** [kissygalleryteam/kissy-gallery#128]
开启多图上传时，比如图片最大数目是3，那么如果同时选择5个图片，1 2 3 5四张图片会上传，并且，第5张图片显示上传中状态，并且图片传到服务器。

原因是，图片作为一个数组贮存在`files`属性中，删除多余的图时，比如上面例子，会从4号图片开始删除，4号图删除之后，数组上了一个元素，原来的5号图片占据4的位置，下一步删除5的时候，5对应的图已经找不到了，修复方案是，从后向前删除图片。

此外，图片过多时，就算正常调用了`queue.remove()`方法，图片还是会多传一张上去，这个不知道怎么处理好。我现在的处理是，选择图片的时候就去掉多余的图片。

**Comment by yiminghe** [comment]
@minghe see

**Comment by shepherdwind** [comment]
这个好像转移到kf上去了。
