### ISSUE TITLE
waterfall部分图片重叠

### ISSUE THREAD

**Issue by edeye** [kissygalleryteam/kissy-gallery#135]
使用bootstrap2.3.1+kissy1.3.0-waterfall组件+jquery1.9.1出现图片重叠的情况
去掉加载的bootstrap.min.css就可以正常显示

对应的复现demo在图片中，直接下载图片，修改后缀为rar用winrar打开就是可以看到现象的demo

![newpic](https://f.cloud.github.com/assets/3690451/271500/8a68a1ec-8fe7-11e2-938a-4daf784ba1d3.jpg)

**Comment by yiminghe** [comment]
模板修改为：
<img height="{{height}}" alt="{{title}}" style='height:{{height}}px' src="http://farm{{farm}}.static.flickr.com/{{server}}/{{id}}_{{secret}}_m.jpg" />
