### ISSUE TITLE
Slider组件bug

### ISSUE THREAD

**Issue by chunterg** [kissygalleryteam/kissy-gallery#148]
@jayli 

1.panel元素只支持div
2.panel实际个数少于显示个数时，初始化报错

**Comment by yiminghe** [comment]
到这 https://github.com/kissygalleryteam/slide/issues

**Comment by jayli** [comment]
增加了延时处理，升级到1.1即可

**Comment by jayli** [comment]
1.panel元素只支持div
2.panel实际个数少于显示个数时，初始化报错

pannel目前只支持div，为什么需要支持其他元素？

第二个问题在1.1版本中修复
