### ISSUE TITLE
【KF/Number】组件review建议

### ISSUE THREAD

**Issue by minghe** [kissygalleryteam/kissy-gallery#55]
- demo场景覆盖不够（demo页面至少需要额外二个demo，覆盖Number的60%常用的API）
- 钩子不符合规范，应该是<code>.J_PriceInput</code>
- <code>#!/price/plus</code>url变化意义不大，建议修改，首先为什么加“!”，这个数字增减器，不只单纯针对price，建议修改，<code>plus</code>这个可以使用更通俗的<code>add</code>，我的建议去掉，如果确定加hash，可以考虑实现后面加数字记忆的功能，比如#num/45，当然这个功能本身没太大意义。
- 看下文档<a href="http://www.36ria.com/demo/gal/gallery/form/1.2/doc/symbols/Number.html">Number</a>，注释有些部分内容可以优化的
  所有函数都是公有方法？
- <code>addHTML()</code>、<code>eventOnChangeNum()</code>很多方法多余用户来说不会调用到，建议加“_”。
- <code>eventOnChangeNum</code>使用<code>_changeHandler</code>更为的简洁？
- <code>accessible</code>的配置项，比较多余，无障碍应该是必选项。
- <code>trigger</code>配置有缺陷，测试下页面出现多个Number的情况，会出bug，这个需要修正，请以target为基点，去寻找trigger节点，这样才能保证对应性。

```
getTrigger = self.get('trigger'), $plus = $(getTrigger.plus), $minus = $(getTrigger.minus)
```
- 建议去掉<code>trigger</code>配置，增减二个触发器，组件内置就好，用户基本不会手动修改。
- <code> ks-price-input</code>组件的class命名一定要有通用性，不要出现price这种指向性特别明显的词语

```
 cls: {
                value: {
                    init: 'ks-price-input',
                    plus: 'ks-number-plus',
                    minus: 'ks-number-minus',
                    container: 'ks-plus-minus-operation'
                }
            }
```
- 函数有返回值，会是个好习惯，特别是公有函数。
- <code>$target.addAttr('aria-label','出价框，请输入价格');</code>移植不完整，label内容倒可以让用户去自定义。

**Comment by minghe** [comment]
$containerEl.append($minusEl).append($target).append($plusEl);
$parent.append($containerEl);
这段可优化，dom的添加可以一次性完成，而不是一个个插入。

**Comment by minghe** [comment]
inputValue = +$target.val(); "+"号写法建议使用更通俗的Number($target.val());缺少S.trim()，清空输入框的两端空白

**Comment by minghe** [comment]
$plus.on('click', function(){  
                inputValue = +$target.val();
                inputValue += range;
                limitRange.call(self,  inputValue);
            });
            $minus.on('click',function(){

```
            inputValue = +$target.val();
            inputValue -= range;
            limitRange.call(self, inputValue);
        })
```

这二个事件监听器内容很接近，比较重复，可以考虑独立个_handler()出来处理。

**Comment by minghe** [comment]
limitRange = self.limitRange;
limitRange.call(self, inputValue);
非常别扭的写法。self.limitRange(inputValue);没重新改变上下文的需求，还是别用call

**Comment by minghe** [comment]
var $ = Node.all, D = S.DOM; 别混合使用node和DOM

**Comment by flyinhigh** [comment]
eventOnChangeNum使用_changeHandler更为的简洁？我觉得命名应该体现函数的功能，如果用后者不能看出来这个函数是做什么用的。

**Comment by flyinhigh** [comment]
我决定把Number改为SpinBox了，因为HTML5对这个组件有现成的定义，用Number做名字会与js本身的Number对象冲突。

**Comment by minghe** [comment]
SpinBox会不会意思表达不到位，第一眼没明白它是干什么的。

**Comment by flyinhigh** [comment]
网上搜一下应该就知道了，跟combobox一样，已经算是一种约定俗成的称谓。

**Comment by flyinhigh** [comment]
var $ = Node.all, D = S.DOM; 别混合使用node和DOM，这个是因为没找到Node的create方法，所以就直接用DOM.create了。。。

**Comment by minghe** [comment]
好，可以。同学顺便看下网上的类似组件的API设计，和功能。是不是可以补充的。

**Comment by minghe** [comment]
close
