### ISSUE TITLE
【KF/Uploader】flash丢失cookies问题

### ISSUE THREAD

**Issue by minghe** [kissygalleryteam/kissy-gallery#83]

**Comment by appleseedez** [comment]
由于flash player 的bug, 在非IE浏览器下,  上传的请求会忽略浏览器中所有的cookie. 如果恰好服务器又对该次请求进行了cookie校验的话. 上传是会失败滴. 
解决的方法: 请和服务端的亲认真商量~ 
祝你的上传应用永不跨域~ 这样你就不会遇到这个恼人的问题鸟! =.0

**Comment by minghe** [comment]
症状描述：非IE下使用flash上传，前端请求发送正常，服务器返回403。由于cookies丢失，服务器的webx框架当获取session进行校验时异常，后面图片的数据变成空。

这是flash的老大难问题，后续想办法解决ajax的上传的跨域支持。
